name: Mirror To Private Repo

on: [push, delete, create]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: spyoungtech/mirror-action@master
          with:
            REMOTE: ${{ secrets.DEST_REPO }}
            GIT_USERNAME: ${{ secrets.DEST_USERNAME }}
            GIT_PASSWORD: ${{ secrets.DEST_PASSWORD }}